FROM node:20.18-alpine AS builder

WORKDIR /app

RUN apk update

COPY front-end/package.json .
RUN npm install

COPY front-end/ .
RUN npm run build
RUN chmod -R 755 build

FROM nginx:1.15.2-alpine AS release
RUN apk add --no-cache jq 

COPY --from=builder /app/build/ /var/www
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
