FROM node:22.18-alpine AS builder

WORKDIR /app

RUN apk update

COPY package.json .
RUN npm install

COPY . .
RUN npm run build
RUN chmod -R 755 dist

FROM nginx:1.29.1-alpine AS release
RUN apk add --no-cache jq 

COPY --from=builder /app/dist/ /var/www
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
